In [6]:
import pandas as pd
import numpy as np
df1=pd.read_csv('20134.csv',encoding = "GB2312") #import document

In [7]:
from math import radians, cos, sin, asin, sqrt  
def haversine(lon1, lat1, lon2, lat2): # 经度1，纬度1，经度2，纬度2 （十进制度数）  
    # 将十进制度数转化为弧度  
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])   
    # haversine公式  
    dlon = lon2 - lon1   
    dlat = lat2 - lat1   
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2  
    c = 2 * asin(sqrt(a))   
    r = 6371.137 # 地球平均半径，单位为公里
    d=np.around(r*c, decimals=3)
    return d 

In [8]:
import numpy as np
np.set_printoptions(suppress=True)
n=df1.shape[0]
a=np.empty(shape=[n, n])#创建空白矩阵
i=0
while i<n:
    j=i
    while j<n:
        lon1=df1.loc[i]['lng']
        lat1=df1.loc[i]['lat']
        lon2=df1.loc[j]['lng']
        lat2=df1.loc[j]['lat']
        a[i,j]=haversine(lon1,lat1,lon2,lat2)
        j=j+1
    i=i+1  

In [10]:
import pickle
with open('data1.pickle','wb') as file:
    pickle.dump(a,file)

In [9]:
print(a)

[[  0.    272.269 165.264 ...  81.682  72.46   87.13 ]
 [  0.      0.    146.432 ... 212.176 209.133 224.374]
 [  0.      0.      0.    ...  85.625  92.872  89.884]
 ...
 [  0.      0.      0.    ...   0.     17.44   18.683]
 [  0.      0.      0.    ...   0.      0.     35.162]
 [  0.      0.      0.    ...   0.      0.      0.   ]]
